'use client';
import { useEffect,useState } from 'react';
import { addDays,format,parseISO } from 'date-fns';
import { Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis } from 'recharts';
import { BarChart3,BookOpen,CalendarDays,Check,ChevronRight,CloudRain,Flame,House,LayoutDashboard,ListChecks,Pencil,Plus,Settings,ShieldCheck,Sparkles,Target,Trash2,Trophy } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';
import { DataManagement } from '@/components/data-management';
import { TaskDialog } from '@/components/task-dialog';
import { useStudyApp } from '@/hooks/use-study-app';
import { backlogFor,catchUpPlan,clamp,currentStage,dailyRating,daysUntil,getDateKey,levelFromExp,levelProgress,studyStreak,subjectTotals,tasksForDate,weekRange,weeklyRank,weeklyStats } from '@/lib/study-calculations';
import { familyVisitPhase,isFamilyVisitDate,isLearningTask } from '@/lib/study-schedule';
import type { AppSettings,Subject,Task } from '@/lib/study-types';

type View='dashboard'|'quests'|'subjects'|'weekly'|'analytics'|'milestones'|'settings';
const nav:[View,string,React.ElementType][]=[['dashboard','任務總覽',LayoutDashboard],['quests','每日任務',ListChecks],['subjects','科目進度',BookOpen],['weekly','Weekly Quest',Target],['analytics','分析報告',BarChart3],['milestones','里程碑',Trophy],['settings','系統設定',Settings]];
const today=getDateKey();
const fmtHours=(n:number)=>`${Math.max(0,n).toFixed(1)} hr`;

export default function StudyApp(){
  const app=useStudyApp();const {data,totalExp,toggleTask}=app;const [view,setView]=useState<View>('dashboard');const [selectedDate,setSelectedDate]=useState(today);const [dialogOpen,setDialogOpen]=useState(false);const [editing,setEditing]=useState<Task|null>(null);
  const openTask=(task:Task|null)=>{setEditing(task);setDialogOpen(true)};
  useEffect(()=>{if(!data)return;const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options?:{signal?:AbortSignal})=>void}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();context.registerTool({name:'toggle_study_task',title:'切換讀書任務狀態',description:'依任務 ID 完成或取消完成任務，並同步更新畫面進度。',inputSchema:{type:'object',properties:{taskId:{type:'string',minLength:1}},required:['taskId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const taskId=(input as {taskId?:string}).taskId;if(!taskId)throw new Error('任務 ID 不可空白');toggleTask(taskId);return {taskId,status:'updated'}}},{signal:lifecycle.signal});return()=>lifecycle.abort()},[data,toggleTask]);
  if(!data)return <div className="loading">正在載入作戰資料…</div>;
  const tasks=tasksForDate(data.tasks,selectedDate);const level=levelProgress(totalExp);const stage=currentStage();const decoratedSubjects=data.subjects.map(s=>subjectTotals(data,s));
  const pageTitle={dashboard:'今日作戰台',quests:'任務編成',subjects:'科目戰力',weekly:'Weekly Quest',analytics:'分析報告',milestones:'里程碑路線',settings:'系統設定'}[view];
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Sparkles size={18}/></span><span>GRAD//QUEST</span></div><nav aria-label="主要導覽">{nav.map(([id,label,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}><Icon size={19}/>{label}</button>)}</nav><div className="player-card"><div className="avatar">{level.level}</div><div><b>{data.player.name}</b><small>穩定累積，比完美更重要</small></div></div></aside>
    <section className="workspace"><header className="topbar"><div><p className="eyebrow">{format(new Date(),'yyyy 年 M 月 d 日')}・研究所備考</p><h1>{pageTitle}</h1></div><div className="stage-pill"><span>STAGE {stage.n}</span>{stage.name}</div></header>
      {view==='dashboard'&&<Dashboard data={data} tasks={tasksForDate(data.tasks,today)} subjects={decoratedSubjects} totalExp={totalExp} toggle={app.toggleTask} add={()=>openTask(null)} navigate={setView}/>} 
      {view==='quests'&&<Quests data={data} selectedDate={selectedDate} setSelectedDate={setSelectedDate} tasks={tasks} toggle={app.toggleTask} edit={openTask} remove={app.deleteTask} add={()=>openTask(null)} reschedule={app.rescheduleDay}/>}
      {view==='subjects'&&<Subjects data={data} subjects={decoratedSubjects} updateSubject={app.updateSubject}/>} 
      {view==='weekly'&&<Weekly data={data} settle={app.settleWeek}/>} 
      {view==='analytics'&&<Analytics data={data} subjects={decoratedSubjects}/>} 
      {view==='milestones'&&<Milestones data={data} subjects={decoratedSubjects}/>} 
      {view==='settings'&&<SettingsView data={data} save={app.updateSettings} exportData={app.exportData} importData={app.importData} clearData={app.clearData}/>} 
    </section><TaskDialog open={dialogOpen} onOpenChange={setDialogOpen} task={editing} date={selectedDate} subjects={data.subjects} onSave={app.saveTask}/></main>;
}

function LevelCard({exp,streak}:{exp:number;streak:number}){const l=levelProgress(exp);return <section className="level-card panel"><div className="level-row"><div><span className="muted">PLAYER LEVEL</span><strong>LV. {l.level}</strong></div><span className="rank">RANK {l.level>=20?'S':l.level>=12?'A':l.level>=6?'B':'C'}</span></div><div className="xp-label"><span>{l.current.toLocaleString()} EXP</span><span>{l.needed.toLocaleString()}</span></div><div className="bar"><i style={{width:`${l.percent}%`}}/></div><div className="mini-stats"><span><Flame size={17}/>{streak} 天 Streak</span><span>◈ {Math.floor(exp/10)} 金幣</span></div></section>}
function Ring({value}:{value:number}){return <div className="progress-ring" style={{'--progress':`${clamp(value)*3.6}deg`} as React.CSSProperties}><div><strong>{Math.round(value)}%</strong><span>核心完成度</span></div></div>}
function Dashboard({data,tasks,subjects,totalExp,toggle,add,navigate}:{data:ReturnType<typeof useStudyApp>['data']&{};tasks:Task[];subjects:Subject[];totalExp:number;toggle:(id:string)=>void;add:()=>void;navigate:(v:View)=>void}){const result=dailyRating(tasks,data.settings.passPercent,{settings:data.settings,date:today});const streak=studyStreak(data);const family=isFamilyVisitDate(data.settings,today);return <><ModeBanner data={data}/><div className="status-grid"><LevelCard exp={totalExp} streak={streak}/><section className="panel completion"><Ring value={result.rate}/><div><b>{tasks.filter(t=>isLearningTask(t)&&t.completed).length} / {tasks.filter(isLearningTask).length}</b><span>{result.rating}</span><small>{family?`完成 ${data.settings.familyLearningMinimumMinutes} 分鐘最低學習即可 PASS`:`核心任務達 ${data.settings.passPercent}% 即可通關`}</small></div></section><Countdown title="第一階段截止" date={data.settings.phaseDeadline}/><Countdown title="研究所考試" date={data.settings.examDate} gold/></div><div className="content-grid"><section className="panel quest-panel"><div className="section-title"><div><span className="eyebrow">DAILY QUEST</span><h2>今日任務</h2></div><button className="primary" onClick={add}><Plus size={14}/>新增任務</button></div><TaskList tasks={tasks} data={data} toggle={toggle}/><div className={`pass-note ${result.rating!=='未通關'?'passed':''}`}><span>PASS LINE</span><p>{result.rating==='未通關'?(family?'今天以陪伴家人為主，完成最低維持即可延續 Streak':'完成核心任務的合理比例即可延續 Streak'):'今日已通關，剩餘任務可依體力調整'}</p><strong>{Math.round(result.rate)}%</strong></div></section><aside className="right-column"><section className="panel subject-panel"><div className="section-title"><div><span className="eyebrow">SUBJECT STATUS</span><h2>科目戰力</h2></div><button className="ghost" onClick={()=>navigate('subjects')}>全部 <ChevronRight size={13}/></button></div>{subjects.map(s=><SubjectBar key={s.id} subject={s}/>)}</section><section className="panel recovery-card"><div className="recovery-icon">✦</div><div><span className="eyebrow">RECOVERY STATUS</span><h2>午餐、午休與睡眠已保留</h2><p>休息也是長期作戰的一部分。</p></div><span className="unlocked">ALWAYS ON</span></section></aside></div></>}
function ModeBanner({data}:{data:NonNullable<ReturnType<typeof useStudyApp>['data']>}){const phase=familyVisitPhase(data.settings,today);if(!phase&&!data.settings.rainyDayMode)return null;return <section className={`mode-banner ${phase?'family-mode':'rain-mode'}`}>{phase?<House size={18}/>:<CloudRain size={18}/>}<div><span className="eyebrow">{phase?'FAMILY VISIT MODE':'RAINY DAY MODE'}</span><b>{phase?`本週模式：返鄉週・${phase}`:'通勤已增加為 30 分鐘'}</b><p>{phase?'今日以陪伴家人與最低學習維持為優先。':'Main Quest 優先；午休、睡眠與晚間自由不被壓縮。'}</p></div></section>}
function Countdown({title,date,gold}:{title:string;date:string;gold?:boolean}){return <section className={`panel countdown ${gold?'exam':''}`}><span className="muted">{title}</span><strong>{daysUntil(date)}</strong><b>天</b><small><CalendarDays size={15}/>{date.replaceAll('-',' / ')}</small></section>}
function TaskList({tasks,data,toggle,controls}:{tasks:Task[];data:NonNullable<ReturnType<typeof useStudyApp>['data']>;toggle:(id:string)=>void;controls?:{edit:(t:Task)=>void;remove:(id:string)=>void}}){if(!tasks.length)return <div className="empty-state"><ShieldCheck size={28}/><b>這天沒有任務</b><span>留白也是排程的一部分。</span></div>;const labels:Record<Task['type'],string>={video:'VIDEO',practice:'PRACTICE',review:'REVIEW',english:'ENGLISH',school:'SCHOOL',recovery:'RECOVERY',commute:'COMMUTE',family:'FAMILY','weekly-review':'WEEKLY REVIEW'};return <div>{[...tasks].sort((a,b)=>(a.scheduledStart||'23:59').localeCompare(b.scheduledStart||'23:59')).map(t=>{const s=data.subjects.find(x=>x.id===t.subjectId);const learning=isLearningTask(t);return <article className={`quest ${!learning?'recovery':''} ${t.completed?'is-done':''}`} key={t.id}><Checkbox checked={t.completed} onCheckedChange={()=>toggle(t.id)} className="task-checkbox"/><div className="subject-dot" style={{background:s?.color||'#6fbea3'}}/><div className="quest-copy"><span>{t.mainQuest?'MAIN QUEST':labels[t.type]} · {s?.shortName||(!learning?'行程':'恢復')}</span><h3>{t.title}</h3><p>{t.scheduledStart?`${t.scheduledStart}${t.scheduledEnd?`–${t.scheduledEnd}`:''} · `:''}{t.plannedMinutes} 分鐘{t.questionCount?` · ${t.questionCount} 題`:''}{t.adjustment?` · ${t.adjustment}`:''}</p></div><strong className="exp">{learning?`+${Math.round(t.exp*data.settings.expMultiplier)} EXP`:'不計 EXP'}</strong>{controls&&<div className="row-actions"><button onClick={()=>controls.edit(t)} aria-label="編輯"><Pencil size={15}/></button><button onClick={()=>controls.remove(t.id)} aria-label="刪除"><Trash2 size={15}/></button></div>}</article>})}</div>}
function SubjectBar({subject}:{subject:Subject}){const value=subject.originalVideoHours?clamp(subject.completedOriginalHours/subject.originalVideoHours*100):clamp(subject.reviewHours/4*100);return <div className="subject"><div className="subject-top"><span><i style={{background:subject.color}}/><b>{subject.name}</b></span><em>LV.{levelFromExp(subject.exp)}</em></div><div className="bar subtle"><i style={{width:`${value}%`,background:subject.color}}/></div><div className="subject-meta"><span>{subject.originalVideoHours?`${subject.completedOriginalHours.toFixed(1)} / ${subject.originalVideoHours} 原始小時`:`本週輔助科目`}</span><b>{Math.round(value)}%</b></div></div>}

function Quests({data,selectedDate,setSelectedDate,tasks,toggle,edit,remove,add,reschedule}:{data:NonNullable<ReturnType<typeof useStudyApp>['data']>;selectedDate:string;setSelectedDate:(d:string)=>void;tasks:Task[];toggle:(id:string)=>void;edit:(t:Task)=>void;remove:(id:string)=>void;add:()=>void;reschedule:(date:string,wake:string)=>void}){const days=Array.from({length:7},(_,i)=>format(addDays(parseISO(weekRange(parseISO(selectedDate)).start),i),'yyyy-MM-dd'));const [wakeDrafts,setWakeDrafts]=useState<Record<string,string>>({});const wakeTime=wakeDrafts[selectedDate]||data.settings.wakeOverrides[selectedDate]||(parseISO(selectedDate).getDay()===1?data.settings.mondayWakeTime:data.settings.defaultWakeTime);const rating=dailyRating(tasks,data.settings.passPercent,{settings:data.settings,date:selectedDate});return <section className="panel page-panel"><div className="section-title"><div><span className="eyebrow">QUEST PLANNER</span><h2>本週任務</h2></div><button className="primary" onClick={add}><Plus size={14}/>新增任務</button></div><div className="date-strip">{days.map(d=><button className={d===selectedDate?'active':''} onClick={()=>setSelectedDate(d)} key={d}><span>{['日','一','二','三','四','五','六'][parseISO(d).getDay()]}</span><b>{parseISO(d).getDate()}</b><i>{data.tasks.filter(t=>t.date===d&&isLearningTask(t)&&t.completed).length}/{data.tasks.filter(t=>t.date===d&&isLearningTask(t)).length}</i></button>)}</div><div className="tolerance-bar"><div><b>晚起容錯</b><span>輸入實際起床時間；Main Quest 優先，Side Quest 縮減，不補到深夜。</span></div><input aria-label="實際起床時間" type="time" value={wakeTime} onChange={e=>setWakeDrafts(d=>({...d,[selectedDate]:e.target.value}))}/><button className="secondary" onClick={()=>reschedule(selectedDate,wakeTime)}>套用調整</button></div><div className="quest-heading"><div><h3>{selectedDate}</h3><p>固定課程與 12:00–14:00 午餐午休不安排讀書任務</p></div><span>{rating.rating}</span></div><TaskList tasks={tasks} data={data} toggle={toggle} controls={{edit,remove}}/></section>}
function Subjects({data,subjects,updateSubject}:{data:NonNullable<ReturnType<typeof useStudyApp>['data']>;subjects:Subject[];updateSubject:(s:Subject)=>void}){return <div className="subject-cards">{subjects.map(s=>{const backlog=backlogFor(data,s);const actualNeed=s.originalVideoHours/s.speed;return <section className="panel subject-detail" key={s.id}><div className="subject-card-head"><i style={{background:s.color}}/><div><span>{s.shortName.toUpperCase()} PATH</span><h2>{s.name}</h2></div><b>LV. {levelFromExp(s.exp)}</b></div>{s.originalVideoHours>0?<><div className="big-progress"><strong>{Math.round(backlog?.percent||0)}%</strong><span>影片進度</span></div><div className="bar"><i style={{width:`${backlog?.percent||0}%`,background:s.color}}/></div><div className="metric-grid"><div><span>原始課程</span><b>{s.completedOriginalHours.toFixed(1)} / {s.originalVideoHours} hr</b></div><div><span>{s.speed}× 實際需求</span><b>{(s.completedOriginalHours/s.speed).toFixed(1)} / {actualNeed.toFixed(1)} hr</b></div><div><span>題目</span><b>{s.questions} 題</b></div><div><span>複習</span><b>{s.reviewHours.toFixed(1)} hr</b></div></div><div className={`pace ${backlog?.behind?'behind':'ahead'}`}>{backlog?.behind?<>目前落後 {backlog.behind.toFixed(1)} 原始小時；平均每週多完成 {backlog.extraPerWeek.toFixed(1)} 小時即可平順補回。</>:<>目前進度正常或超前 {backlog?.ahead.toFixed(1)} 小時，維持節奏即可。</>}</div></>:<div className="metric-grid english-grid"><div><span>本週目標</span><b>{data.settings.weeklyTargets.english} hr</b></div><div><span>累積複習</span><b>{s.reviewHours.toFixed(1)} hr</b></div><div><span>題目／單字</span><b>{s.questions}</b></div><div><span>科目 EXP</span><b>{s.exp}</b></div></div>}<div className="inline-settings"><label>倍速<input type="number" min="0.5" max="3" step="0.05" value={s.speed} disabled={s.id==='english'} onChange={e=>updateSubject({...s,speed:Math.max(.5,+e.target.value)})}/></label><label>原始總時數<input type="number" min="0" value={s.originalVideoHours} disabled={s.id==='english'} onChange={e=>updateSubject({...s,originalVideoHours:Math.max(0,+e.target.value)})}/></label></div></section>})}</div>}
function Weekly({data,settle}:{data:NonNullable<ReturnType<typeof useStudyApp>['data']>;settle:(w:string,r:string)=>void}){const w=weeklyStats(data);const rows=[['研究所總學習',w.graduateHours,w.targetStudyHours],['英文',w.english,w.targetEnglishHours],['經濟影片',w.economics,data.settings.weeklyTargets.economics*.55],['財管影片',w.finance,data.settings.weeklyTargets.finance*.55],['統計影片',w.statistics,data.settings.weeklyTargets.statistics*.55],['複習＋題目',w.reviewQuestions,w.targetStudyHours*.36]] as const;const rating=weeklyRank(w.overall);const settled=data.settledWeeks.includes(w.start);const catchup=catchUpPlan(data);const modeLabel=w.type==='family'?'Family Visit Week':w.type==='recovery'?'Recovery / Special Week':'Normal Week';return <div className="weekly-layout"><section className="panel weekly-score"><span className="eyebrow">{modeLabel}</span><strong>{rating}</strong><Ring value={w.overall}/><h2>{w.overall>=70?'本週已達目前模式的攻略線':'穩穩累積，不必一次追回'}</h2><p>{w.start} — {w.end}<br/>目標 {w.targetStudyHours.toFixed(1)} 小時＋英文 {w.targetEnglishHours.toFixed(1)} 小時</p><button className="primary" disabled={settled} onClick={()=>settle(w.start,rating)}>{settled?'本週已結算':'結算本週並領取 EXP'}</button></section><section className="panel page-panel"><div className="section-title"><div><span className="eyebrow">WEEKLY KPI · {modeLabel}</span><h2>本週任務進度</h2></div><b>{Math.round(w.overall)}%</b></div>{rows.map(([name,value,target])=><div className="kpi-row" key={name}><div><b>{name}</b><span>{fmtHours(value)} / {target.toFixed(1)} hr</span></div><div className="bar"><i style={{width:`${clamp(value/target*100)}%`}}/></div><strong>{Math.max(0,target-value).toFixed(1)} hr 待完成</strong></div>)}<div className="recommendation"><Target size={20}/><div><b>{catchup.active?'返鄉後平順補進度':'本週節奏建議'}</b><p>{catchup.active?`返鄉週差額約 ${catchup.deficit.toFixed(1)} 小時；未來 ${catchup.weeks} 週每週最多增加 ${catchup.weeklyAddition.toFixed(1)} 小時。若影片預測仍能如期完成，就不必全部補回。`:w.type==='family'?'返鄉週以 Input / Review Mode 為主，Rank 已按降低後的動態目標計算。':'優先補足完成率較低的科目，每天最多增加 60–90 分鐘，不把差額塞到隔天。'}</p></div></div></section></div>}
function Analytics({data,subjects}:{data:NonNullable<ReturnType<typeof useStudyApp>['data']>;subjects:Subject[]}){const seven=Array.from({length:7},(_,i)=>{const d=getDateKey(addDays(new Date(),i-6));return {day:format(parseISO(d),'MM/dd'),hours:data.tasks.filter(t=>t.date===d&&t.completed).reduce((s,t)=>s+t.actualMinutes/60,0)}});return <div className="analytics-grid"><section className="panel chart-panel"><div className="section-title"><div><span className="eyebrow">LAST 7 DAYS</span><h2>讀書時間</h2></div></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><BarChart data={seven}><CartesianGrid stroke="#24313a" vertical={false}/><XAxis dataKey="day" stroke="#73808a" fontSize={11}/><YAxis stroke="#73808a" fontSize={11}/><Tooltip contentStyle={{background:'#11181e',border:'1px solid #2b3a45',borderRadius:8}}/><Bar dataKey="hours" fill="#7fa8df" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></section><section className="panel page-panel"><span className="eyebrow">FORECAST</span><h2>預測完成日期</h2>{subjects.filter(s=>s.originalVideoHours).map(s=>{const b=backlogFor(data,s);const forecast=b?.forecastDays?format(addDays(new Date(),b.forecastDays),'yyyy/MM/dd'):'資料不足';return <div className="forecast" key={s.id}><span><i style={{background:s.color}}/>{s.name}</span><b>{forecast}</b></div>})}<p className="forecast-note">預測會依已完成影片與目前速度更新；資料不足時不會顯示錯誤日期。</p></section><section className="panel page-panel analytics-wide"><span className="eyebrow">TOTAL INVESTMENT</span><h2>各科投入</h2><div className="investment-bars">{subjects.map(s=>{const hours=s.completedOriginalHours/s.speed+s.reviewHours;return <div key={s.id}><span>{s.name}</span><div className="bar"><i style={{width:`${clamp(hours/40*100)}%`,background:s.color}}/></div><b>{hours.toFixed(1)} hr</b></div>})}</div></section></div>}
function Milestones({data,subjects}:{data:NonNullable<ReturnType<typeof useStudyApp>['data']>;subjects:Subject[]}){const overall=subjects.filter(s=>s.originalVideoHours).reduce((a,s)=>a+s.completedOriginalHours,0)/400*100;return <section className="panel page-panel"><div className="section-title"><div><span className="eyebrow">CAMPAIGN ROADMAP</span><h2>9 月至 12 月攻略路線</h2></div><b>目前 {Math.round(overall)}%</b></div><div className="timeline">{data.milestones.map((m,i)=><div className={`milestone ${overall>=m.targetPercent?'complete':''}`} key={m.id}><div className="milestone-node">{overall>=m.targetPercent?<Check size={16}/>:i+1}</div><div><span>{m.date}</span><h3>{m.title}</h3><p>{m.description}</p></div><strong>{m.targetPercent}%</strong></div>)}</div></section>}
function SettingsView({data,save,exportData,importData,clearData}:{data:NonNullable<ReturnType<typeof useStudyApp>['data']>;save:(s:AppSettings)=>void;exportData:()=>string;importData:(raw:string)=>void;clearData:()=>void}){
  const [draft,setDraft]=useState(data.settings);useEffect(()=>setDraft(data.settings),[data.settings]);
  const patch=<K extends keyof AppSettings>(k:K,v:AppSettings[K])=>setDraft(d=>({...d,[k]:v}));
  const patchFamily=<K extends keyof AppSettings['familyVisit']>(k:K,v:AppSettings['familyVisit'][K])=>setDraft(d=>({...d,familyVisit:{...d.familyVisit,[k]:v}}));
  return <div className="settings-grid">
    <section className="panel page-panel"><span className="eyebrow">CAMPAIGN CONFIG</span><h2>日期、生活作息與通關規則</h2><div className="form-grid settings-form">
      <label>第一階段截止<input type="date" value={draft.phaseDeadline} onChange={e=>patch('phaseDeadline',e.target.value)}/></label><label>影片目標日<input type="date" value={draft.videoDeadline} onChange={e=>patch('videoDeadline',e.target.value)}/></label><label>研究所考試日<input type="date" value={draft.examDate} onChange={e=>patch('examDate',e.target.value)}/></label><label>每日最大讀書時數<input type="number" min="1" max="16" step="0.5" value={draft.maxDailyHours} onChange={e=>patch('maxDailyHours',Math.max(1,+e.target.value))}/></label>
      <label>一般起床時間<input type="time" value={draft.defaultWakeTime} onChange={e=>patch('defaultWakeTime',e.target.value)}/></label><label>星期一起床時間<input type="time" value={draft.mondayWakeTime} onChange={e=>patch('mondayWakeTime',e.target.value)}/></label><label>一般週研究所目標<input type="number" min="20" max="50" step="0.5" value={draft.normalWeeklyStudyHours} onChange={e=>patch('normalWeeklyStudyHours',Math.max(20,+e.target.value))}/></label><label>英文每週目標<input type="number" min="0" max="10" step="0.25" value={draft.englishWeeklyHours} onChange={e=>patch('englishWeeklyHours',Math.max(0,+e.target.value))}/></label>
      <label>通關百分比<input type="number" min="50" max="100" value={draft.passPercent} onChange={e=>patch('passPercent',clamp(+e.target.value,50,100))}/></label><label>EXP 倍率<input type="number" min="0.25" max="5" step="0.25" value={draft.expMultiplier} onChange={e=>patch('expMultiplier',Math.max(.25,+e.target.value))}/></label>
      <label className="switch-line" htmlFor="rainy-mode"><input id="rainy-mode" aria-label="Rainy Day 雨天模式" type="checkbox" checked={draft.rainyDayMode} onChange={e=>patch('rainyDayMode',e.target.checked)}/><span><b>Rainy Day／雨天模式</b><small>上課前通勤改為 30 分鐘；優先縮減 Side Quest，不壓縮午休與睡眠。</small></span></label>
      <label>週類型<select value={draft.weekTypeOverride} onChange={e=>patch('weekTypeOverride',e.target.value as AppSettings['weekTypeOverride'])}><option value="auto">自動判斷</option><option value="normal">Normal Week</option><option value="recovery">Recovery / Special Week</option></select></label>
    </div></section>
    <section className="panel page-panel"><span className="eyebrow">FAMILY VISIT MODE</span><h2>返鄉週設定</h2><div className="form-grid">
      <label className="switch-line" htmlFor="family-mode"><input id="family-mode" aria-label="啟用返鄉模式" type="checkbox" checked={draft.familyVisit.enabled} onChange={e=>patchFamily('enabled',e.target.checked)}/><span><b>啟用返鄉模式</b><small>切換為 Input / Review Mode，不要求週末補回一般負荷。</small></span></label>
      <label>開始日期<input type="date" value={draft.familyVisit.startDate} onChange={e=>patchFamily('startDate',e.target.value)}/></label><label>結束日期<input type="date" value={draft.familyVisit.endDate} onChange={e=>patchFamily('endDate',e.target.value)}/></label>
      <label className="switch-line" htmlFor="family-current-week"><input id="family-current-week" aria-label="目前週視為返鄉週" type="checkbox" checked={draft.familyVisit.currentWeek} onChange={e=>patchFamily('currentWeek',e.target.checked)}/><span><b>目前週視為返鄉週</b><small>日期未涵蓋時，也可手動套用到本週。</small></span></label>
      <label>每日 Learning Minimum<input type="number" min="30" max="90" step="15" value={draft.familyLearningMinimumMinutes} onChange={e=>patch('familyLearningMinimumMinutes',clamp(+e.target.value,30,90))}/></label>
    </div><button className="primary save-settings" onClick={()=>save(draft)}>儲存並更新排程</button></section>
    <section className="panel page-panel"><span className="eyebrow">FIXED SCHEDULE</span><h2>固定不可排任務時段</h2><div className="schedule-list">{draft.schedule.map(c=><div key={c.id}><span>星期{'日一二三四五六'[c.weekday]}</span><b>{c.title}</b><em>{c.start}–{c.end}</em></div>)}</div><div className="rest-list"><b>固定 Recovery</b>{draft.restWindows.map(r=><span key={r}>{r}</span>)}</div></section>
    <DataManagement exportData={exportData} importData={importData} clearData={clearData}/>
  </div>
}
